# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "hashicorp/precise32"
  
  config.vm.network :forwarded_port, guest: 22, host: 6633, id: "ssh"
  
  config.vm.provider "virtualbox" do |v|
	v.name = "node-test"
  end
  
  config.vm.provision :shell, :inline => "echo \"US/Pacific\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"
  
  config.vm.provision :shell, :path => "bootstrap.sh"
  
  #config.vm.synced_folder "~/node-test", "/node-test"

end
